// background.js - FocusTube service worker (performance-optimized)
//
// Optimization notes:
//  - SETTINGS CACHE: settings are hydrated once from chrome.storage.sync into
//    an in-memory cache. Every GET_SETTINGS after warm-up is a memory read, so
//    chrome.storage.sync is touched only on cold start (fewer async I/O calls).
//  - STATS IN LOCAL STORAGE: statistics were previously nested inside the sync
//    settings object. They now live in chrome.storage.local (no sync quota,
//    much cheaper to write) and are flushed ONCE every 7s in a single write.
//  - MEMORY-FIRST MUTATIONS: keyword/channel/settings changes mutate the cache
//    synchronously so all listeners see the latest state instantly; we persist
//    only the final state, never intermediate ones.
//  - FEWER WAKE-UPS: batched stats flush + batched, debounced writes keep the
//    service worker from being woken/thrashing constantly.

const DEFAULT_SETTINGS = {
  hideBrainrot: true,
  hideAIGenerated: true,
  hideGreenScreen: true,
  brainrotKeywords: [
    'skibidi','skibidi toilet','sigma','sigma male','alpha','alpha male',
    'beta male','gigachad','chad','rizz','the rizzler','gyatt',
    'ohio','only in ohio','fanum tax','mewing','looksmaxxing',
    'looksmax','mogging','mog','edgemaxxing','brain rot','brainrot',
    'aura','+1000 aura','negative aura','npc','npc moment','npc stream',
    'relatable','relatable memes','pov','pov:','that feeling when',
    'when bro','bro really','bro thinks','bro is','bro forgot',
    'cooked','chat is this real','no cap','fr fr','on god',
    'bussin','based','ratio','mid','goated','gooning',
    'grimace shake','grimace','backrooms','liminal space',
    'analog horror','mandela catalogue','uncanny','uncanny meme',
    'smurf cat','bing chilling','cameraman','tv man','speaker man',
    'scientist man','toilet man','the one piece is real',
    'can we get much higher','level up','1000 iq','999 iq',
    'edit','edits','cold edit','hard edit','sigma edit',
    'phonk edit','velocity edit','capcut template',
    'animation meme','gacha','gacha life','gacha club',
    'storytime animation','slime','slime video',
    'oddly satisfying','viral memes','funniest memes',
    'viral shorts','crazy shorts','wait for it',
    'dont scroll','stop scrolling','scroll stopper',
    'gen alpha','gen alpha humor','brainrot compilation'
  ],
  aiGeneratedKeywords: [
    'ai generated','generated by ai','made with ai','created with ai',
    'ai made','made by ai','fully ai','100% ai',
    'ai-generated','ai-generated content','ai label',
    'altered or synthetic','altered or synthetic content',
    'synthetic content','synthetically generated','contains ai',
    'ai video','ai animation','ai short','ai movie',
    'ai story','ai stories','ai facts','ai history',
    'ai explains','ai explained','what if ai',
    'ai future','future predicted by ai',
    'ai art','ai image','ai drawing',
    'ai music','ai cover','ai song','ai remix',
    'ai voice','ai voice over','ai voiceover',
    'clone voice','voice clone',
    'deepfake','deep fake',
    'ai avatar','virtual influencer',
    'text to video','text to image',
    'sora','veo','veo 2','veo 3',
    'runway','pika','luma','dream machine',
    'hailuo','kling','pixverse','hedra',
    'kaiber','midjourney','dalle',
    'stable diffusion','flux ai','leonardo ai',
    'chatgpt generated','chatgpt made',
    'faceless youtube','faceless channel',
    'ai shorts','ai meme','ai memes',
    'ai podcast','ai narrator',
    'text to speech','tts','elevenlabs',
    'ai dub','translated with ai',
    'ai slop','automation channel',
    'fake interview','fake podcast'
  ],
  greenScreenKeywords: [
    'green screen','greenscreen',
    'subway surfers','subway surfers background',
    'minecraft parkour','minecraft gameplay background',
    'gta gameplay background',
    'parkour background',
    'gameplay in background',
    'games in background',
    'background gameplay',
    'gameplay under video',
    'split screen',
    'video on top',
    'video on bottom',
    'family guy clips',
    'family guy funny moments',
    'american dad clips',
    'south park clips',
    'simpsons clips',
    'rick and morty clips',
    'soap cutting',
    'kinetic sand',
    'satisfying gameplay',
    'satisfying videos',
    'satisfying compilation',
    'pressure washing',
    'carpet cleaning',
    'power wash',
    'green screen reaction',
    'greenscreen reaction',
    'fake reaction',
    'pointing reaction',
    'reaction with gameplay',
    'reddit stories gameplay',
    'storytime gameplay',
    'podcast gameplay',
    'aita gameplay',
    'tiktok stories gameplay'
  ],
  blockedChannels: []
};

// ---------------------------------------------------------------------------
// Storage keys
// ---------------------------------------------------------------------------
const STORAGE_KEY = 'focustube_settings';   // sync (small, device-synced settings)
const STATS_KEY = 'focustube_statistics';   // local (large, fast, per-device counters)
const SETTINGS_VERSION = 3;                 // v3: adds YouTube AI disclosure-label keywords

// Batch stats writes to local storage at most once per interval.
const STATS_FLUSH_MS = 7000;

// ---------------------------------------------------------------------------
// In-memory caches (the whole point: avoid repeated chrome.* calls)
// ---------------------------------------------------------------------------
let settingsCache = null;
let settingsPromise = null;
let statsCache = null;
let statsPromise = null;
let statsDirty = false;
let statsFlushTimer = null;

// ---------------------------------------------------------------------------
// Settings: hydrate once, cache forever (within this worker lifetime)
// ---------------------------------------------------------------------------
function dedupe(arr) {
  return [...new Set((arr || []).filter(Boolean).map(s => String(s).trim()).filter(s => s))];
}

function migrateSettings(stored) {
  if (!stored) stored = {};
  if (stored._version === SETTINGS_VERSION) return stored;

  return {
    ...DEFAULT_SETTINGS,
    ...stored,
    brainrotKeywords: dedupe([...DEFAULT_SETTINGS.brainrotKeywords, ...(stored.brainrotKeywords || [])]),
    aiGeneratedKeywords: dedupe([...DEFAULT_SETTINGS.aiGeneratedKeywords, ...(stored.aiGeneratedKeywords || [])]),
    greenScreenKeywords: dedupe([...DEFAULT_SETTINGS.greenScreenKeywords, ...(stored.greenScreenKeywords || [])]),
    _version: SETTINGS_VERSION
  };
}

// sanitize: statistics were previously saved inside settings; we now keep them
// separate in local storage, so drop them before persisting to sync.
function sanitizeForSync(settings) {
  const clean = { ...settings };
  delete clean.statistics;
  return clean;
}

// hydrateSettings memoizes on a single promise so concurrent GET_SETTINGS during
// a cold start collapse into ONE chrome.storage.sync read (never repeated).
async function hydrateSettings() {
  if (settingsCache) return settingsCache;
  if (!settingsPromise) {
    settingsPromise = (async () => {
      try {
        const result = await chrome.storage.sync.get(STORAGE_KEY);
        const stored = result[STORAGE_KEY] || {};
        settingsCache = migrateSettings(stored);
        if (!stored._version || stored._version !== SETTINGS_VERSION) {
          await chrome.storage.sync.set({ [STORAGE_KEY]: sanitizeForSync(settingsCache) });
        }
      } catch (e) {
        settingsCache = migrateSettings({});
      }
      return settingsCache;
    })();
  }
  return settingsPromise;
}

// ---------------------------------------------------------------------------
// Statistics: cached in memory, batched flush to chrome.storage.local
// ---------------------------------------------------------------------------
function emptyStats() {
  return {
    totals: { videosHidden: 0, channelsBlocked: 0, brainrotHidden: 0, aiGeneratedHidden: 0, greenScreenHidden: 0 },
    daily: {},
    weekly: {}
  };
}

function mergeStoredStats(base, stored) {
  if (!stored || typeof stored !== 'object') return base;
  const totals = { ...base.totals };
  ['videosHidden', 'channelsBlocked', 'brainrotHidden', 'aiGeneratedHidden', 'greenScreenHidden'].forEach(k => {
    if (typeof stored.totals?.[k] === 'number') totals[k] = stored.totals[k];
  });
  return { totals, daily: stored.daily || {}, weekly: stored.weekly || {} };
}

// hydrateStats: same single-promise memoization as settings, but for the
// local-storage statistics (read once on cold start).
async function hydrateStats() {
  if (statsCache) return statsCache;
  if (!statsPromise) {
    statsPromise = (async () => {
      const base = emptyStats();
      try {
        const result = await chrome.storage.local.get(STATS_KEY);
        statsCache = mergeStoredStats(base, result[STATS_KEY]);
      } catch (e) {
        statsCache = base;
      }
      return statsCache;
    })();
  }
  return statsPromise;
}

// In-memory-only increments first; disk write is batched (perf: no per-video
// chrome.storage call, no sync write amplification).
async function updateStats(updates) {
  const stats = await hydrateStats();

  const today = new Date().toISOString().split('T')[0];
  const weekStart = getWeekStartDate();

  if (!stats.daily[today]) stats.daily[today] = { videosHidden: 0, channelsBlocked: 0, brainrotHidden: 0, aiGeneratedHidden: 0, greenScreenHidden: 0 };
  if (!stats.weekly[weekStart]) stats.weekly[weekStart] = { videosHidden: 0, channelsBlocked: 0, brainrotHidden: 0, aiGeneratedHidden: 0, greenScreenHidden: 0 };

  Object.keys(updates).forEach(key => {
    const n = updates[key];
    if (typeof n !== 'number') return;
    stats.totals[key] = (stats.totals[key] || 0) + n;
    stats.daily[today][key] = (stats.daily[today][key] || 0) + n;
    stats.weekly[weekStart][key] = (stats.weekly[weekStart][key] || 0) + n;
  });

  statsDirty = true;
  scheduleStatsFlush();
  return snapshotStatistics(stats);
}

// One timer at a time: accumulate updates for up to 7s, then write once.
function scheduleStatsFlush() {
  if (statsDirty && !statsFlushTimer) {
    statsFlushTimer = setTimeout(() => {
      statsFlushTimer = null;
      flushStats();
    }, STATS_FLUSH_MS);
  }
}

async function flushStats() {
  if (!statsDirty) return;
  statsDirty = false;
  const stats = statsCache || await hydrateStats();
  try {
    await chrome.storage.local.set({ [STATS_KEY]: stats });
  } catch (e) { /* non-fatal; retried on next flush */ }
}

function snapshotStatistics(stats) {
  return {
    videosHidden: stats.totals.videosHidden,
    channelsBlocked: stats.totals.channelsBlocked,
    brainrotHidden: stats.totals.brainrotHidden,
    aiGeneratedHidden: stats.totals.aiGeneratedHidden,
    greenScreenHidden: stats.totals.greenScreenHidden,
    daily: stats.daily,
    weekly: stats.weekly
  };
}

function getWeekStartDate() {
  const date = new Date();
  const day = date.getDay();
  const diff = date.getDate() - day;
  const weekStart = new Date(date.setDate(diff));
  return weekStart.toISOString().split('T')[0];
}

function categoryToKey(category) {
  if (category === 'ai' || category === 'aiGenerated') return 'aiGeneratedKeywords';
  if (category === 'greenscreen' || category === 'greenScreen') return 'greenScreenKeywords';
  return 'brainrotKeywords';
}

// Shared helper for handlers that mutate settings: update cache in memory,
// persist the sanitized final state to sync (single write).
async function persistSettings(settings) {
  settingsCache = settings;
  try {
    await chrome.storage.sync.set({ [STORAGE_KEY]: sanitizeForSync(settings) });
  } catch (e) { /* swallow: cache stays authoritative for this worker */ }
}

// ---------------------------------------------------------------------------
// Message handlers — all async responses keep `return true`
// ---------------------------------------------------------------------------
chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'GET_SETTINGS') {
    // One async cold-start read → thereafter purely from memory.
    Promise.all([hydrateSettings(), hydrateStats()]).then(([settings, stats]) => {
      sendResponse({ ...settings, statistics: snapshotStatistics(stats) });
    });
    return true;
  }

  if (message.type === 'SAVE_SETTINGS') {
    persistSettings(message.settings).then(() => sendResponse({ success: true }));
    return true;
  }

  if (message.type === 'UPDATE_STATISTICS') {
    updateStats(message.updates || {}).then(stats => sendResponse({ stats }));
    return true;
  }

  if (message.type === 'RESET_STATISTICS') {
    (async () => {
      const fresh = emptyStats();
      statsCache = fresh;
      statsDirty = true;
      await flushStats(); // flush immediately so a hard reset survives
      sendResponse({ success: true });
    })();
    return true;
  }

  if (message.type === 'ADD_KEYWORD') {
    const category = message.category || 'brainrot';
    const key = categoryToKey(category);
    hydrateSettings().then(settings => {
      const keywords = settings[key] || [];
      if (!keywords.includes(message.keyword)) {
        keywords.push(message.keyword);
        persistSettings(settings).then(() => sendResponse({ success: true }));
      } else {
        sendResponse({ success: false, error: 'Keyword already exists' });
      }
    });
    return true;
  }

  if (message.type === 'REMOVE_KEYWORD') {
    const category = message.category || 'brainrot';
    const key = categoryToKey(category);
    hydrateSettings().then(settings => {
      settings[key] = (settings[key] || []).filter(k => k !== message.keyword);
      persistSettings(settings).then(() => sendResponse({ success: true }));
    });
    return true;
  }

  if (message.type === 'ADD_BLOCKED_CHANNEL') {
    hydrateSettings().then(settings => {
      const channel = { id: message.channelId, name: message.channelName, dateAdded: new Date().toISOString() };
      if (!settings.blockedChannels.find(c => c.id === message.channelId)) {
        settings.blockedChannels.push(channel);
        persistSettings(settings).then(() => sendResponse({ success: true }));
      } else {
        sendResponse({ success: false, error: 'Channel already blocked' });
      }
    });
    return true;
  }

  if (message.type === 'REMOVE_BLOCKED_CHANNEL') {
    hydrateSettings().then(settings => {
      settings.blockedChannels = settings.blockedChannels.filter(c => c.id !== message.channelId);
      persistSettings(settings).then(() => sendResponse({ success: true }));
    });
    return true;
  }
});

chrome.runtime.onInstalled.addListener(async () => {
  // Only initialize if nothing is stored yet (existing users keep their data).
  const existing = await chrome.storage.sync.get(STORAGE_KEY);
  if (existing[STORAGE_KEY]) return;
  const seeded = { ...DEFAULT_SETTINGS, _version: SETTINGS_VERSION };
  await chrome.storage.sync.set({ [STORAGE_KEY]: sanitizeForSync(seeded) });
  await chrome.storage.local.set({ [STATS_KEY]: emptyStats() });
});