// content.js - FocusTube content script (performance-optimized)
//
// Performance design:
//  - NEVER full-page rescans: a WeakSet remembers every element already
//    checked. After the initial seed pass we only examine subtrees that the
//    MutationObserver reports as NEWLY ADDED, so a 500+ video feed is touched
//    exactly once per card.
//  - WeakSet (not a regular Set/array): elements that leave the DOM are
//    garbage-collected automatically -> no memory leaks from stale references.
//  - Debounced MutationObserver (150ms): scroll-spam and rapid DOM churn get
//    coalesced into a single scan pass instead of N passes.
//  - Keywords compiled once into a Set of single words (O(1) lookups) plus a
//    tiny array of phrases; blocked channels into a Set. No per-scroll
//    recompilation, no repeated .includes() over arrays.
//  - Processing runs in small batches inside requestIdleCallback (fallback
//    rAF/timeout) so YouTube paints instantly and long feeds never jank.
//  - Hiding = one classList.add('.focustube-hidden') write (CSS rule in
//    styles/content.css). No inline-style writes, no per-item reflow churn.
//  - Stats accumulate in memory and are sent to the service worker ONCE every
//    5s as one message, instead of one message per hidden video.
//  - The heavy ytInitialData walk is deferred to idle and cached per
//    navigation (only re-walked when a new data object appears).

const CARD_SELECTOR = 'ytd-rich-item-renderer,' +
  'ytd-video-renderer,' +
  'ytd-grid-video-renderer,' +
  'ytd-compact-video-renderer,' +
  'ytd-watch-next-video,' +
  'ytd-reel-item-renderer';

const OBSERVER_DEBOUNCE_MS = 150;
const BATCH_SIZE = 25;           // cards processed per idle callback
const ADDED_NODE_BUDGET = 5000;  // cap queued added-nodes (memory safety)
const QUEUE_COMPACT_AT = 128;    // compact queue index to avoid unbounded array growth
const STATS_SEND_MS = 5000;      // batch stats messages

// Every place YouTube renders a badge on a card/watch page (old Polymer
// ytd-badge-supported-renderer plus the newer Lit yt-simple-badge-view-model).
// Scoping by badge class keeps AI-label checks to a handful of nodes per card.
const BADGE_SELECTOR = 'ytd-badge-supported-renderer,' +
  'yt-simple-badge-view-model,' +
  'span.badge-shape-wiz__text,' +
  '.badge-shape-wiz--text,' +
  '.inline-badge-shape,' +
  '#inline-playback-badges span';

// Label text YouTube uses to disclose AI-generated / synthetic videos. "AI" as
// a standalone badge is the small indicator icon; the rest are the long-form
// disclosure phrases shown on cards, Shorts overlays, and the watch page.
const AI_LABEL_RE = /^ai$|ai[\s-]?generated|generated by ai|made with ai|created with ai|containing ai|altered or synthetic|synthetic content|synthetically generated|ai content/i;

class YouTubeFilter {
  constructor() {
    this.settings = null;
    this.keywords = null;        // { brainrot: {single:Set, phrases:[]}, ai:..., green:... }
    this.blockedIds = new Set(); // channel ids, cached for O(1) checks
    this.processed = new WeakSet(); // elements already evaluated -> never rescanned
    this.pendingElements = [];   // FIFO queue of cards awaiting processing
    this.queueIndex = 0;
    this.idleScheduled = false;
    this.observer = null;
    this.observerTimer = null;
    this.addedNodes = [];        // newly added subtrees waiting to be scanned
    this.badVideos = null;       // Map<videoId, reason> from ytInitialData (id-based match)
    this.lastDataRef = null;     // identity of the last ytInitialData object walked
    this.lastPageType = null;
    this.lastWatchId = null;     // avoid re-checking the same watch page repeatedly
    this.dismissedBanner = {};   // user dismissed banner per videoId
    this.pendingStats = {};      // batched counters
    this.statsTimer = null;
    this.initialized = false;
  }

  init() {
    if (this.initialized) return; // guard: no duplicate listeners ever
    this.initialized = true;

    // One settings fetch on load; afterwards we react to storage events.
    chrome.runtime.sendMessage({ type: 'GET_SETTINGS' }, (response) => {
      if (!response) return;
      this.applySettings(response);
      this.setupMutationObserver();
      this.enqueueSubtree(document.body || document.documentElement); // initial seed pass (the only full scan)
      this.scheduleProcessing();
    });

    // React to settings changes with NO extra message: chrome.storage.onChanged
    // delivers the new settings payload directly (fewer wake-ups, faster).
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area !== 'sync') return;
      const patch = changes && changes.focustube_settings && changes.focustube_settings.newValue;
      if (!patch) return;
      this.applySettings(patch);
      // Settings may enable/disable filters: reveal previously hidden cards and
      // re-evaluate the whole page once (rare event, so a full pass is fine).
      this.unhideAll();
      this.processed = new WeakSet();
      this.enqueueSubtree(document.body || document.documentElement);
      this.scheduleProcessing();
    });

    // SPA navigation: new page content + possibly new ytInitialData.
    window.addEventListener('yt-navigate-finish', () => this.onNavigation());
    window.addEventListener('popstate', () => this.onNavigation());
  }

  // Rebuild compiled keyword Sets + channel Set whenever settings change.
  applySettings(settings) {
    this.settings = settings;
    this.keywords = {
      brainrot: this.compileCategory(settings.brainrotKeywords),
      ai: this.compileCategory(settings.aiGeneratedKeywords),
      green: this.compileCategory(settings.greenScreenKeywords)
    };
    this.blockedIds = new Set((settings.blockedChannels || []).map(c => c.id));
  }

  compileCategory(list) {
    // Single words go into a Set (O(1) token lookup); multi-word phrases stay
    // in a small array because substring matching can't be hashed.
    const single = new Set();
    const phrases = [];
    for (const raw of list || []) {
      let k = String(raw).trim().toLowerCase();
      if (!k) continue;
      if (/\s/.test(k)) {
        phrases.push(k);
        continue;
      }
      // Normalize single words: strip boundary punctuation (e.g. "pov:")
      // so they match the tokenized title text.
      k = k.replace(/^[^a-z0-9]+|[^a-z0-9]+$/g, '');
      if (k) single.add(k);
    }
    return { single, phrases };
  }

  onNavigation() {
    // New page = new video ids + new ytInitialData object.
    this.badVideos = null;
    this.lastDataRef = null;
    this.lastWatchId = null;
    // Scan the fresh page-manager subtree once; the observer handles the rest.
    this.enqueueSubtree(document.querySelector('ytd-page-manager') || document.body);
    this.scheduleProcessing();
    this.scheduleIdle(() => {
      this.ensureBadVideoMap();
      this.checkWatchPage();
    });
  }

  // ---------------------------------------------------------------------
  // Scanning: only NEW subtrees, debounced and batched
  // ---------------------------------------------------------------------

  setupMutationObserver() {
    const target = document.documentElement;
    if (!target || this.observer) return;

    this.observer = new MutationObserver((mutations) => {
      // Cheap collection stage: only remember which nodes were ADDED. No DOM
      // queries here, so mutations on a scrolling feed cost almost nothing.
      let budget = ADDED_NODE_BUDGET;
      for (const mutation of mutations) {
        for (const node of mutation.addedNodes) {
          if (budget-- <= 0) break;
          if (node && node.nodeType === 1) this.addedNodes.push(node);
        }
      }
      // Debounce: coalesce bursts of mutations (scrolling, shelf loading) into
      // a single scan instead of one scan per mutation batch.
      clearTimeout(this.observerTimer);
      this.observerTimer = setTimeout(() => this.flushAddedNodes(), OBSERVER_DEBOUNCE_MS);
    });

    this.observer.observe(target, { childList: true, subtree: true });
  }

  flushAddedNodes() {
    const nodes = this.addedNodes;
    this.addedNodes = [];
    if (!nodes.length) return;
    for (const node of nodes) this.enqueueSubtree(node);
    this.scheduleProcessing();
  }

  // Extract candidate cards from ONE subtree only (never the whole document).
  enqueueSubtree(node) {
    if (!node || node.nodeType !== 1) return;
    const queue = this.pendingElements;

    // The added node itself may be a card (e.g. inline-expand rows).
    if (node.matches && node.matches(CARD_SELECTOR)) {
      if (!this.processed.has(node)) {
        this.processed.add(node); // mark immediately -> no double-queuing
        queue.push(node);
      }
    }
    // Cards nested inside the new subtree (typical case: a new shelf/row).
    const found = node.querySelectorAll(CARD_SELECTOR);
    for (const el of found) {
      if (!this.processed.has(el)) {
        this.processed.add(el);
        queue.push(el);
      }
    }
  }

  // ---------------------------------------------------------------------
  // Idle-batched processing (never blocks the paint/scroll)
  // ---------------------------------------------------------------------

  scheduleProcessing() {
    if (this.idleScheduled) return;
    this.idleScheduled = true;
    this.scheduleIdle(() => {
      this.idleScheduled = false;
      this.processPendingBatch();
    });
  }

  scheduleIdle(fn) {
    // requestIdleCallback runs work in browser idle time; timeout guarantees
    // progress even when the tab stays busy. rAF/timeout are fallbacks.
    if (typeof requestIdleCallback === 'function') {
      requestIdleCallback(fn, { timeout: 2000 });
    } else if (typeof requestAnimationFrame === 'function') {
      requestAnimationFrame(fn);
    } else {
      setTimeout(fn, 16);
    }
  }

  processPendingBatch() {
    const queue = this.pendingElements;
    const end = Math.min(this.queueIndex + BATCH_SIZE, queue.length);

    for (let i = this.queueIndex; i < end; i++) {
      this.checkElement(queue[i]);
    }
    this.queueIndex = end;

    if (this.queueIndex >= queue.length) {
      // Queue drained: free the array, then lazily finish id-based matching
      // and the watch-page check (both deferred to idle).
      queue.length = 0;
      this.queueIndex = 0;
      this.scheduleIdle(() => {
        this.ensureBadVideoMap();
        this.checkWatchPage();
      });
      return;
    }
    // Compact periodically so the queue array doesn't grow without bound.
    if (this.queueIndex >= QUEUE_COMPACT_AT) {
      queue.splice(0, this.queueIndex);
      this.queueIndex = 0;
    }
    this.scheduleProcessing();
  }

  // ---------------------------------------------------------------------
  // Per-card check (one card, a handful of small queries)
  // ---------------------------------------------------------------------

  checkElement(el) {
    // 1) Lazily built id->reason map from ytInitialData (fast path).
    const videoId = this.getVideoId(el);
    if (videoId && this.badVideos && this.badVideos.has(videoId)) {
      this.hide(el, this.badVideos.get(videoId));
      return;
    }

    // 2) Blocked channel (O(1) Set lookup).
    const channelId = this.getChannelId(el);
    if (channelId && this.blockedIds.has(channelId)) {
      this.hide(el, 'channelsBlocked');
      return;
    }

    // 3) Keyword/badge detection.
    const title = this.getVideoTitle(el);
    const channel = this.getChannelName(el);
    if (!title && !channel) return;

    const reason = this.reasonFor(title, channel, this.getCardText(el), this.hasAIBadge(el));
    if (reason) this.hide(el, reason);
  }

  hide(el, reason) {
    // One CSS-class write (no inline-style mutations) -> faster than
    // setting style.display and cheaper for the compositor.
    el.classList.add('focustube-hidden');
    this.trackStat(reason);
  }

  unhideAll() {
    const els = document.querySelectorAll('.focustube-hidden');
    for (const el of els) el.classList.remove('focustube-hidden');
  }

  getVideoId(el) {
    const link = el.querySelector('a[href*="watch?v="], a[href*="/shorts/"], a[href*="embed/"]');
    if (!link) return null;
    const href = link.href || '';
    const m = href.match(/[?&]v=([^&]+)/);
    if (m) return m[1];
    const m2 = href.match(/\/(?:shorts|embed)\/([^/?&]+)/);
    return m2 ? m2[1] : null;
  }

  getVideoTitle(el) {
    const t = el.querySelector('#video-title, #video-title-link, a#video-title, .title, a[title]');
    if (t) {
      const attrTitle = t.getAttribute && t.getAttribute('title');
      if (attrTitle) return attrTitle.trim();
      if (t.textContent) return t.textContent.trim();
    }
    // Fallback: thumbnail aria-label contains "Title by Channel".
    const thumb = el.querySelector('a#thumbnail[aria-label], a.yt-simple-endpoint[aria-label]');
    if (thumb) return (thumb.getAttribute('aria-label') || '').trim();

    const reel = el.querySelector('#reel-item-title, [id*="reel-item-title"]');
    if (reel) return reel.textContent.trim();
    return '';
  }

  getChannelName(el) {
    const c = el.querySelector(
      'ytd-channel-name #text, ytd-channel-name a, .channel-info a, ' +
      'ytd-video-meta-block ytd-channel-name a, a[href*="/@"], a[href*="/channel/"]'
    );
    if (c) {
      const text = c.textContent.trim();
      if (text) return text;
    }
    const thumb = el.querySelector('a#thumbnail[aria-label]');
    if (thumb) {
      const label = thumb.getAttribute('aria-label') || '';
      return (label.split('by ').pop() || label).trim();
    }
    return '';
  }

  getChannelId(el) {
    const link = el.querySelector('ytd-channel-name a[href*="/"], .channel-info a[href*="/"], a[href*="/channel/"], a[href*="/@"]');
    return link ? this.extractChannelId(link.href || link.getAttribute('href')) : null;
  }

  getCardText(el) {
    // Extra context (descriptions / announcement text) for better recall.
    let text = '';
    const desc = el.querySelector('#description-text, ytd-video-meta-block #description-text, .metadata-description');
    if (desc) text += ' ' + desc.textContent;
    // Badge text is included so badge phrases funnel through keyword matching.
    const overlays = el.querySelectorAll(BADGE_SELECTOR);
    for (const o of overlays) text += ' ' + o.textContent;
    return text;
  }

  hasAIBadge(el) {
    // Scan only badge-shaped nodes (a handful per card) and test each against
    // the AI-label regex. Never searches the whole card text for "AI".
    const nodes = el.querySelectorAll(BADGE_SELECTOR);
    for (const n of nodes) {
      if (this.isAILabel(n.textContent)) return true;
    }
    return false;
  }

  // Single source of truth for "is this badge text an AI marker". The length
  // cap prevents matching against large text blobs that happen to sit inside a
  // badge container.
  isAILabel(text) {
    if (!text) return false;
    const t = text.trim().toLowerCase();
    return t.length <= 60 && AI_LABEL_RE.test(t);
  }

  reasonFor(title, channel, extraText, aiBadge) {
    const s = this.settings;
    const text = `${title} ${channel} ${extraText || ''}`.toLowerCase();
    // Tokenize once per card; word Set lookups are O(1) per token.
    const tokens = text.match(/[a-z0-9]+/g) || [];

    if (s.hideBrainrot && this.matchKeywords(text, tokens, this.keywords.brainrot)) return 'brainrotHidden';
    if (s.hideAIGenerated && aiBadge) return 'aiGeneratedHidden';
    if (s.hideAIGenerated && this.matchKeywords(text, tokens, this.keywords.ai)) return 'aiGeneratedHidden';
    if (s.hideGreenScreen && this.matchKeywords(text, tokens, this.keywords.green)) return 'greenScreenHidden';
    return null;
  }

  matchKeywords(text, tokens, kw) {
    if (!kw) return false;
    // Phrases (rare) via substring; single words via the Set.
    if (kw.phrases.length && kw.phrases.some(p => text.includes(p))) return true;
    if (kw.single.size) {
      for (const t of tokens) {
        if (kw.single.has(t)) return true;
      }
    }
    return false;
  }

  // ---------------------------------------------------------------------
  // ytInitialData id-based detection (deferred to idle, cached per nav)
  // ---------------------------------------------------------------------

  ensureBadVideoMap() {
    if (this.badVideos) return;              // already built for this navigation
    const data = window.ytInitialData;
    if (!data) { this.badVideos = new Map(); return; }
    if (data === this.lastDataRef) return;   // same object, nothing new to walk

    this.lastDataRef = data;
    this.badVideos = new Map();
    this.visitData(data, this.badVideos, 0);

    const wpr = window.ytInitialPlayerResponse;
    if (wpr && wpr.videoDetails && wpr.videoDetails.videoId) {
      const vd = wpr.videoDetails;
      const reason = this.reasonFor(vd.title || '', vd.author || '', '', this.hasAIBadge(document));
      if (reason) this.badVideos.set(vd.videoId, reason);
    }
  }

  visitData(node, map, depth) {
    if (!node || depth > 14 || typeof node !== 'object') return;

    if (Array.isArray(node)) {
      for (const item of node) this.visitData(item, map, depth + 1);
      return;
    }

    for (const key of ['videoRenderer', 'compactVideoRenderer']) {
      const r = node[key];
      if (r && typeof r === 'object' && r.videoId) this.inspectVideoData(r, map);
    }
    if (node.shortsLockupViewModel) this.inspectShortsData(node.shortsLockupViewModel, map);

    for (const key of Object.keys(node)) {
      if (key === 'videoRenderer' || key === 'compactVideoRenderer' || key === 'shortsLockupViewModel') continue;
      const value = node[key];
      if (value && typeof value === 'object') this.visitData(value, map, depth + 1);
    }
  }

  inspectVideoData(r, map) {
    const id = r.videoId;
    const title = this.extractText(r.title);
    const owner = this.extractText(r.ownerText) || this.extractText(r.longBylineText) || '';
    const extra = this.extractDescriptionText(r) + ' ' + this.extractBadgeText(r);

    if (this.blockedIds.has(id)) { map.set(id, 'channelsBlocked'); return; }

    const reason = this.reasonFor(title, owner, extra, this.hasBadgeLabel(this.extractBadgeText(r)));
    if (reason) map.set(id, reason);
  }

  inspectShortsData(s, map) {
    let videoId = null;
    try {
      videoId = s.onTap && s.onTap.innertubeCommand && (s.onTap.innertubeCommand.reelWatchEndpoint || {}).videoId;
    } catch (e) { /* ignore */ }

    const title = (s.overlayMetadata && s.overlayMetadata.primaryText && s.overlayMetadata.primaryText.content) || '';
    const owner = (s.overlayMetadata && s.overlayMetadata.secondaryText && s.overlayMetadata.secondaryText.content) || '';
    if (!videoId || !title) return;

    // Shorts carry their disclosure as an overlay badge -> feed it through the
    // same label check used elsewhere (covers the bare "AI" indicator too).
    const badgeText = this.extractShortsBadgeText(s);
    const reason = this.reasonFor(title, owner, badgeText, this.hasBadgeLabel(badgeText));
    if (reason) map.set(videoId, reason);
  }

  extractText(obj) {
    if (!obj) return '';
    if (typeof obj === 'string') return obj;
    if (Array.isArray(obj.runs)) return obj.runs.map(r => (r && r.text) || '').join('');
    if (obj.simpleText) return obj.simpleText;
    if (obj.content) return obj.content;
    return '';
  }

  extractBadgeText(r) {
    const parts = [];
    // Badges appear in two shapes: old metadataBadgeRenderer or the newer
    // metadataBadgeViewModel (text.content). ownerBadges carries channel ones.
    const badges = [...(r.badges || []), ...(r.ownerBadges || [])];
    for (const b of badges) {
      if (!b) continue;
      if (b.metadataBadgeRenderer && b.metadataBadgeRenderer.label) {
        parts.push(b.metadataBadgeRenderer.label);
      } else if (b.metadataBadgeViewModel) {
        const t = this.extractText(b.metadataBadgeViewModel.text);
        if (t) parts.push(t);
      }
    }
    return parts.join(' ');
  }

  extractShortsBadgeText(s) {
    // Overlay badges on Shorts cards (e.g. "AI" indicator / disclosure label).
    const parts = [];
    const ob = s.overlayBadges;
    if (!ob) return '';
    const list = Array.isArray(ob) ? ob : (ob.shortsLockupBadgeViewModels || ob.badges || []);
    for (const b of list) {
      if (!b) continue;
      const t = this.extractText(b && (b.text || b.label || b.title));
      if (t) parts.push(t);
    }
    return parts.join(' ');
  }

  extractDescriptionText(r) {
    if (r.detailedMetadataSnippets && r.detailedMetadataSnippets.length) {
      return this.extractText(r.detailedMetadataSnippets[0].snippetText);
    }
    if (r.descriptionSnippet) return this.extractText(r.descriptionSnippet);
    return '';
  }

  hasBadgeLabel(badgeText) {
    // Data path reuses the same label regex as the DOM path.
    return this.isAILabel(badgeText);
  }

  // ---------------------------------------------------------------------
  // Watch page banner (checked once per video, after idle)
  // ---------------------------------------------------------------------

  checkWatchPage() {
    if (this.getPageType() !== 'watch') return;

    const videoId = this.getCurrentVideoId();
    if (!videoId || this.dismissedBanner[videoId]) return;
    if (document.getElementById('focustube-warning')) return;
    if (this.lastWatchId === videoId) return; // already evaluated this video

    this.lastWatchId = videoId;

    const title = document.title.replace(/ - YouTube$/, '').trim();
    const channelNode = document.querySelector('ytd-watch-metadata ytd-channel-name a, #owner ytd-channel-name a, a[href*="/@"][id*="channel"]');
    const channel = channelNode ? channelNode.textContent.trim() : '';
    const channelHref = channelNode ? (channelNode.href || channelNode.getAttribute('href')) : '';

    const desc = document.querySelector('#description-inline-expander, ytd-text-inline-expander, #description ytd-text-inline-expander');
    const extra = desc ? desc.textContent : '';

    const reason = this.reasonFor(title, channel, extra, this.hasAIBadge(document));
    if (!reason) return;

    this.showWarning(videoId, reason, channel, channelHref);
  }

  showWarning(videoId, reason, channelName, channelHref) {
    if (document.getElementById('focustube-warning')) return;

    const banner = document.createElement('div');
    banner.id = 'focustube-warning';

    const reasonLabels = {
      brainrotHidden: 'brain rot',
      aiGeneratedHidden: 'AI-generated',
      greenScreenHidden: 'green screen',
      channelsBlocked: 'blocked channel'
    };

    const header = document.createElement('div');
    header.className = 'focustube-warning-title';
    header.textContent = 'FocusTube';

    const text = document.createElement('p');
    text.textContent = `This video may be ${reasonLabels[reason] || 'low-quality'} content.`;

    const actions = document.createElement('div');
    actions.className = 'focustube-warning-actions';

    if (channelName) {
      const blockBtn = document.createElement('button');
      blockBtn.textContent = `Block channel: ${channelName}`;
      blockBtn.addEventListener('click', () => {
        const channelId = this.extractChannelId(channelHref);
        chrome.runtime.sendMessage({
          type: 'ADD_BLOCKED_CHANNEL',
          channelId: channelId || channelName,
          channelName
        }, (response) => {
          if (response && response.success) {
            blockBtn.textContent = 'Channel blocked';
            blockBtn.disabled = true;
          }
        });
      });
      actions.appendChild(blockBtn);
    }

    const dismissBtn = document.createElement('button');
    dismissBtn.textContent = 'Dismiss';
    dismissBtn.addEventListener('click', () => {
      this.dismissedBanner[videoId] = true;
      banner.remove();
      // Bound the dismissed map so it can't grow forever (memory safety).
      const keys = Object.keys(this.dismissedBanner);
      if (keys.length > 200) delete this.dismissedBanner[keys[0]];
    });
    actions.appendChild(dismissBtn);

    banner.appendChild(header);
    banner.appendChild(text);
    banner.appendChild(actions);

    const target = document.querySelector('#primary, ytd-watch-flexy, #contents');
    if (target) target.prepend(banner);
  }

  getPageType() {
    const path = window.location.pathname;
    if (path === '/') return 'home';
    if (path === '/shorts' || path.startsWith('/shorts/')) return 'shorts';
    if (path.startsWith('/results')) return 'search';
    if (path.startsWith('/watch')) return 'watch';
    return 'other';
  }

  getCurrentVideoId() {
    const urlParams = new URLSearchParams(window.location.search);
    const videoId = urlParams.get('v') ||
      (window.location.pathname.match(/^\/watch\/([^?&]+)/) || [])[1] ||
      (window.location.pathname.match(/^\/(?:shorts|video)\/([^?&]+)/) || [])[1];
    return videoId;
  }

  extractChannelId(url) {
    if (!url) return null;
    const match = url.match(/\/channel\/([^/?&]+)/);
    if (match) return match[1];
    const handle = url.match(/\/@([^/?&]+)/);
    if (handle) return handle[1];
    const match2 = url.match(/\/c\/([^/?&]+)/);
    if (match2) return match2[1];
    const match3 = url.match(/\/user\/([^/?&]+)/);
    if (match3) return match3[1];
    return null;
  }

  // ---------------------------------------------------------------------
  // Batched statistics (one message per 5s, not one per video)
  // ---------------------------------------------------------------------

  trackStat(type) {
    if (type !== 'channelsBlocked') {
      this.pendingStats.videosHidden = (this.pendingStats.videosHidden || 0) + 1;
    }
    this.pendingStats[type] = (this.pendingStats[type] || 0) + 1;

    if (!this.statsTimer) {
      this.statsTimer = setTimeout(() => this.flushStats(), STATS_SEND_MS);
    }
  }

  flushStats() {
    this.statsTimer = null;
    const updates = this.pendingStats;
    this.pendingStats = {};
    if (Object.keys(updates).length) {
      chrome.runtime.sendMessage({ type: 'UPDATE_STATISTICS', updates });
    }
  }
}

const focusTube = new YouTubeFilter();

// Detach everything cleanly; safety net so nothing outlives the page.
window.addEventListener('beforeunload', () => {
  if (focusTube.observer) focusTube.observer.disconnect();
  clearTimeout(focusTube.observerTimer);
  if (focusTube.statsTimer) {
    focusTube.flushStats(); // persist any pending counters on unload
  }
});

if (document.readyState === 'complete') {
  focusTube.init();
} else {
  window.addEventListener('load', () => {
    focusTube.init();
  });
}